// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzqpzFgg8MlywgkAWoqNEqJc4hwjej5_0',
    appId: '1:780453798245:web:d3a9590497ecea0c99018c',
    messagingSenderId: '780453798245',
    projectId: 'demo2-c3023',
    authDomain: 'demo2-c3023.firebaseapp.com',
    storageBucket: 'demo2-c3023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxAQdWN8XVgU7DyX1XZlMWLOIZUmAKdkI',
    appId: '1:780453798245:android:b2ef84c8809bb81499018c',
    messagingSenderId: '780453798245',
    projectId: 'demo2-c3023',
    storageBucket: 'demo2-c3023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7ypwShKcXs5PwqnjY0BlHbo-VVW9q4hQ',
    appId: '1:780453798245:ios:9227860760ddb2f599018c',
    messagingSenderId: '780453798245',
    projectId: 'demo2-c3023',
    storageBucket: 'demo2-c3023.appspot.com',
    iosBundleId: 'com.example.demo2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7ypwShKcXs5PwqnjY0BlHbo-VVW9q4hQ',
    appId: '1:780453798245:ios:363bdb3f4c619ef599018c',
    messagingSenderId: '780453798245',
    projectId: 'demo2-c3023',
    storageBucket: 'demo2-c3023.appspot.com',
    iosBundleId: 'com.example.demo2.RunnerTests',
  );
}
